# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sdq3IPDDBq-9Gemob004qbfvxAvxtLe
"""



9

9 + 9 - (10 * 3) - 3

9 + 9 - 10 * 3 - 3



10 + 5

10 * 4

10 * 2



"""10 * 2"""

10 ** 2

10 / 5

10 // 5

15 % 2

12 / 5

12 // 5

x = 10

x = 10
x

x = 10
x = x + 2
x

x = 10

x + 2

x + 2

x

x = 10

x = x + 2

x = x + 2
print(x)
y=10
print(y)
x *= 2
print (x)

x = 10
x = x + 2
print(x)
y=10
print(y)
x *= 2
print (x)

n=10
m=-n
m